name: Product Release Workflow

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to build'
        required: true
        type: string
      release_notes:
        description: 'Release notes'
        required: false
        type: string

permissions:
  contents: write
  id-token: write

jobs:
  macos_build:
    runs-on: ${{ matrix.runner }}
    environment: production
    name: "Release for Mac OS"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: macos-latest
            arch: arm64
          - runner: macos-13
            arch: x64
    steps:
      - name: Checkout Repository Source Code
        uses: actions/checkout@v4
        with:
          path: 'repository'

      - name: Install Apple Certificate and Provisioning Profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # Create variables for certificate and keychain paths
          CERTIFICATE_PATH="${{ runner.temp }}/build_certificate.p12"
          KEYCHAIN_PATH="${{ runner.temp }}/buildagent.keychain"

          # Decode and import certificate from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH

          # Create and configure temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # Import the certificate to the keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
          security find-identity $KEYCHAIN_PATH

      - name: Set up Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Project Dependencies
        working-directory: ./repository
        run: npm install

      - name: Build Mac OS Executables
        working-directory: ./repository
        run: npm run gulp vscode-darwin-${{ matrix.arch }}-min

      - name: Code Sign Application
        working-directory: ./repository
        env:
          VSCODE_ARCH: ${{ matrix.arch }}
          CODESIGN_IDENTITY: ${{ env.CODESIGN_IDENTITY }}
          AGENT_TEMPDIRECTORY: ${{ runner.temp }}
        run: node build/darwin/sign.js "${{ github.workspace }}"

      - name: Package Application for Distribution
        working-directory: ./VSCode-darwin-${{ matrix.arch }}
        run: ditto -c -k --sequesterRsrc --keepParent "Codingle.app" "macos-${{ matrix.arch }}-app.zip"

      - name: Install macOS Build Dependencies
        run: |
          brew install jq # Ensure jq is available for parsing notarytool output

      - name: Submit Application for Notarization
        id: notarize_submit
        working-directory: ./VSCode-darwin-${{ matrix.arch }}
        run: |
          echo "Submitting for notarization..."
          SUBMISSION_OUTPUT=$(xcrun notarytool submit "macos-${{ matrix.arch }}-app.zip" \
            --apple-id "${{ secrets.MACOS_NOTARIZATION_APPLE_ID }}" \
            --team-id "${{ secrets.MACOS_NOTARIZATION_TEAM_ID }}" \
            --password "${{ secrets.MACOS_NOTARIZATION_APP_PASSWORD }}" \
            --output-format json)

          echo "Submission output: $SUBMISSION_OUTPUT"
          REQUEST_UUID=$(echo "$SUBMISSION_OUTPUT" | jq -r '.id')

          if [ -z "$REQUEST_UUID" ] || [ "$REQUEST_UUID" == "null" ]; then
            echo "Failed to get submission UUID."
            echo "Full notarytool output:"
            echo "$SUBMISSION_OUTPUT"
            exit 1
          fi
          echo "REQUEST_UUID=$REQUEST_UUID" >> $GITHUB_ENV
          echo "::set-output name=request_uuid::$REQUEST_UUID"

      - name: Wait for Notarization
        working-directory: ./VSCode-darwin-${{ matrix.arch }}
        run: |
          echo "Waiting for notarization of request: ${{ env.REQUEST_UUID }}"
          MAX_CHECKS=180 # 180 checks * 30 seconds = 90 minutes, adjust as needed
          COUNT=0
          while [ $COUNT -lt $MAX_CHECKS ]; do
            echo "Checking notarization status (attempt $((COUNT+1)))..."
            STATUS_OUTPUT=$(xcrun notarytool info "${{ env.REQUEST_UUID }}" \
              --apple-id "${{ secrets.MACOS_NOTARIZATION_APPLE_ID }}" \
              --team-id "${{ secrets.MACOS_NOTARIZATION_TEAM_ID }}" \
              --password "${{ secrets.MACOS_NOTARIZATION_APP_PASSWORD }}" \
              --output-format json)

            echo "Status output: $STATUS_OUTPUT"
            STATUS=$(echo "$STATUS_OUTPUT" | jq -r '.status')

            if [ "$STATUS" == "Accepted" ]; then
              echo "Notarization successful!"
              LOG_URL=$(echo "$STATUS_OUTPUT" | jq -r '.logFileUrl')
              if [ "$LOG_URL" != "null" ] && [ ! -z "$LOG_URL" ]; then
                echo "Notarization log available at: $LOG_URL"
                # Consider downloading the log: curl -L -o notarization_log.json "$LOG_URL"
              fi
              exit 0
            elif [ "$STATUS" == "Rejected" ] || [ "$STATUS" == "Invalid" ]; then
              echo "Notarization failed with status: $STATUS"
              LOG_URL=$(echo "$STATUS_OUTPUT" | jq -r '.logFileUrl')
              if [ "$LOG_URL" != "null" ] && [ ! -z "$LOG_URL" ]; then
                echo "Notarization log available at: $LOG_URL"
                echo "Attempting to download log..."
                curl -L -o notarization_log.json "$LOG_URL"
                echo "Log content (first 50 lines):"
                head -n 50 notarization_log.json
              else
                echo "No log file URL provided in status output."
              fi
              exit 1
            fi

            echo "Current status: $STATUS. Waiting 30 seconds..."
            sleep 30
            COUNT=$((COUNT+1))
          done
          echo "Timed out waiting for notarization after $MAX_CHECKS checks."
          exit 1

      - name: Staple Notarization to Application
        working-directory: ./VSCode-darwin-${{ matrix.arch }}
        run: xcrun stapler staple "Codingle.app"

      - name: Upload Application Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ matrix.arch }}-app
          path: "VSCode-darwin-${{ matrix.arch }}/macos-${{ matrix.arch }}-app.zip"

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: "VSCode-darwin-${{ matrix.arch }}/macos-${{ matrix.arch }}-app.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux_build:
    runs-on: ${{ matrix.runner }}
    environment: production
    name: "Release for Linux"
    timeout-minutes: 60
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-24.04-arm
            arch: arm64
          - runner: ubuntu-24.04
            arch: x64
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
        with:
          path: 'repository'
          ref: ${{ github.event.inputs.release_tag || github.event.release.tag_name }}

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: repository/node_modules
          key: ${{ runner.os }}-${{ runner.arch }}-node-${{ hashFiles('repository/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-node-

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: 'repository/package-lock.json'

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Linux Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ libx11-dev libxkbfile-dev libsecret-1-dev libkrb5-dev python-is-python3 fakeroot rpm libcups2-dev

      - name: Install Project Dependencies
        working-directory: ${{ github.workspace }}/repository
        run: npm install

      - name: Build Codingle Executables
        working-directory: ./repository
        run: npm run gulp vscode-linux-${{ matrix.arch }}-min

      - name: Prepare Debian Package Files
        working-directory: ./repository
        run: npm run gulp vscode-linux-${{ matrix.arch }}-prepare-deb

      - name: Build Debian Package
        working-directory: ./repository
        run: npm run gulp vscode-linux-${{ matrix.arch }}-build-deb

      - name: Rename Debian Package
        working-directory: ${{ github.workspace }}/repository/.build/linux/deb/${{ matrix.arch == 'x64' && 'amd64' || 'arm64' }}/deb
        run: mv *.deb linux-${{ matrix.arch }}.deb

      - name: Upload Debian Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.arch }}-deb
          path: ${{ github.workspace }}/repository/.build/linux/deb/${{ matrix.arch == 'x64' && 'amd64' || 'arm64' }}/deb/linux-${{ matrix.arch }}.deb

      - name: Prepare RPM Package Files
        working-directory: ./repository
        run: npm run gulp vscode-linux-${{ matrix.arch }}-prepare-rpm

      - name: Build RPM Package
        working-directory: ./repository
        run: npm run gulp vscode-linux-${{ matrix.arch }}-build-rpm

      - name: Rename RPM Package
        working-directory: ${{ github.workspace }}/repository/.build/linux/rpm/${{ matrix.arch == 'x64' && 'x86_64' || 'aarch64' }}
        run: mv *.rpm linux-${{ matrix.arch }}.rpm

      - name: Upload RPM Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.arch }}-rpm
          path: ${{ github.workspace }}/repository/.build/linux/rpm/${{ matrix.arch == 'x64' && 'x86_64' || 'aarch64' }}/linux-${{ matrix.arch }}.rpm

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.workspace }}/repository/.build/linux/deb/${{ matrix.arch == 'x64' && 'amd64' || 'arm64' }}/deb/linux-${{ matrix.arch }}.deb
            ${{ github.workspace }}/repository/.build/linux/rpm/${{ matrix.arch == 'x64' && 'x86_64' || 'aarch64' }}/linux-${{ matrix.arch }}.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup Temporary Files
        if: always()
        run: |
          rm -rf "${{ github.workspace }}/repository/.build"
          rm -rf "${{ github.workspace }}/repository/node_modules"

  windows_build:
    runs-on: 'windows-latest'
    environment: production
    name: "Release for Windows"
    timeout-minutes: 60
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      npm_config_arch: ${{ matrix.arch == 'x64' && 'x64' || 'arm64' }}
    strategy:
      fail-fast: false
      matrix:
        target: [user, system]
        arch: [x64, arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: 'repository'
          ref: ${{ github.event.inputs.release_tag || github.event.release.tag_name }}

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: repository/node_modules
          key: ${{ runner.os }}-${{ matrix.arch }}-node-${{ hashFiles('repository/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.arch }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: 'repository/package-lock.json'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0

      - name: Install dependencies
        working-directory: ${{ github.workspace }}/repository
        run: npm install

      - name: Build Executables
        working-directory: ./repository
        run: npm run gulp vscode-win32-${{ matrix.arch }}-min

      - name: Apply Inno Setup Updater
        working-directory: ./repository
        run: npm run gulp vscode-win32-${{ matrix.arch }}-inno-updater

      - name: Debug- List Files to Sign
        run: |
          echo "Listing contents of ${{ github.workspace }}/repository/.build/"
          dir ${{ github.workspace }}/repository/.build
          echo "Attempting to list contents of ${{ github.workspace }}/VSCode-win32-${{ matrix.arch }}/"
          dir ${{ github.workspace }}/VSCode-win32-${{ matrix.arch }} -ErrorAction SilentlyContinue

      - name: Create Installer
        working-directory: ./repository
        run: npm run gulp vscode-win32-${{ matrix.arch }}-${{ matrix.target }}-setup

      - name: Cosign the Installer
        env:
          COSIGN_EXPERIMENTAL: "1" # Enable keyless signing with GitHub OIDC token
        run: |
          cosign sign-blob --yes --output-signature ${{ github.workspace }}/repository/.build/win32-${{ matrix.arch }}/${{ matrix.target }}-setup/Codingle.exe.sig ${{ github.workspace }}/repository/.build/win32-${{ matrix.arch }}/${{ matrix.target }}-setup/Codingle.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ matrix.arch }}-${{ matrix.target }}-exe
          path: ${{ github.workspace }}/repository/.build/win32-${{ matrix.arch }}/${{ matrix.target }}-setup/Codingle.exe

      - name: Rename Installer and Signature
        working-directory: ${{ github.workspace }}/repository/.build/win32-${{ matrix.arch }}/${{ matrix.target }}-setup
        run: |
          mv Codingle.exe windows-${{ matrix.arch }}-${{ matrix.target }}.exe
          mv Codingle.exe.sig windows-${{ matrix.arch }}-${{ matrix.target }}.exe.sig

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.workspace }}/repository/.build/win32-${{ matrix.arch }}/${{ matrix.target }}-setup/windows-${{ matrix.arch }}-${{ matrix.target }}.exe
            ${{ github.workspace }}/repository/.build/win32-${{ matrix.arch }}/${{ matrix.target }}-setup/windows-${{ matrix.arch }}-${{ matrix.target }}.exe.sig
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup Temporary Files
        if: always()
        run: |
          Remove-Item -Path "${{ github.workspace }}/repository/.build" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item -Path "${{ github.workspace }}/repository/node_modules" -Recurse -Force -ErrorAction SilentlyContinue
